{% set version = "0.7.0" %}

package:
  name: azint
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - pybind11
    
  run:
    - python
    - numpy
    
test:
  source_files:
    - tests/*.py
    - tests/test.poni
  requires:
    - pytest
    - psutil
  commands:
    - pytest tests/

 
