package:
  name: azint
  version: '{{ SETUPTOOLS_SCM_PRETEND_VERSION }}'

source:
  path: ..

build:
  number: 1
  script: pip install .
requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - pybind11
    - setuptools_scm
    
  run:
    - python
    - numpy
    
test:
  source_files:
    - tests/*.py
    - tests/test.poni
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  license: MIT
  license_file: ../LICENSE

 
