name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
    - name: Install conda-build
      shell: bash -l {0}
      run: conda install conda-build
    - name: Build package
      shell: bash -l {0}
      run: |
        conda build $GITHUB_WORKSPACE --output-folder=$GITHUB_WORKSPACE
    - name: Prepare artifacts
      shell: bash -l {0}
      run: |
        mkdir $GITHUB_WORKSPACE/artifacts
        cp $GITHUB_WORKSPACE/*/*.bz2 $GITHUB_WORKSPACE/artifacts/
        ls -l $GITHUB_WORKSPACE/artifacts
    - name: Upload Conda Packages as artifact
      uses: actions/upload-artifact@v1
      with:
        name: upload-conda-packages
        path: artifacts
