name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
    - name: Install conda-build
      shell: bash -l {0}
      run: conda install conda-build
    - name: Build package
      shell: bash -l {0}
      run: |
        conda build $GITHUB_WORKSPACE --output-folder=$GITHUB_WORKSPACE
    - uses: actions/upload-artifact@v3
      with:
        name: package-${{ github.sha }}
        path: ${{ github.workspace }}/**/azint*.bz2
     
