name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda-build
      run: |
        conda install conda-build
    - name: Build package
      run: |
        conda build $GITHUB_WORKSPACE --output-folder=$GITHUB_WORKSPACE
    - name: Prepare artifacts
      run: |
        mkdir $GITHUB_WORKSPACE/artifacts
        cp $GITHUB_WORKSPACE/linux-64/*.bz2 $GITHUB_WORKSPACE/artifacts/
        ls -l $GITHUB_WORKSPACE/artifacts
    - name: Upload Conda Packages as artifact
      uses: actions/upload-artifact@v1
      with:
        name: upload-conda-packages
        path: artifacts
